/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_biletnikov_hotkeys_GlobalKeyboardHook_DLLStateThread */

#ifndef _Included_com_biletnikov_hotkeys_GlobalKeyboardHook_DLLStateThread
#define _Included_com_biletnikov_hotkeys_GlobalKeyboardHook_DLLStateThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
