/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class de_alfah_popup_jni_KeyboardHookThread */

#ifndef _Included_de_alfah_popup_jni_KeyboardHookThread
#define _Included_de_alfah_popup_jni_KeyboardHookThread
#ifdef __cplusplus
extern "C" {
#endif
#undef de_alfah_popup_jni_KeyboardHookThread_MIN_PRIORITY
#define de_alfah_popup_jni_KeyboardHookThread_MIN_PRIORITY 1L
#undef de_alfah_popup_jni_KeyboardHookThread_NORM_PRIORITY
#define de_alfah_popup_jni_KeyboardHookThread_NORM_PRIORITY 5L
#undef de_alfah_popup_jni_KeyboardHookThread_MAX_PRIORITY
#define de_alfah_popup_jni_KeyboardHookThread_MAX_PRIORITY 10L
/*
 * Class:     de_alfah_popup_jni_KeyboardHookThread
 * Method:    checkHotKey
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_alfah_popup_jni_KeyboardHookThread_checkHotKey
  (JNIEnv *, jobject);

/*
 * Class:     de_alfah_popup_jni_KeyboardHookThread
 * Method:    setHotKey
 * Signature: (IZZZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_alfah_popup_jni_KeyboardHookThread_setHotKey
  (JNIEnv *, jobject, jint, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     de_alfah_popup_jni_KeyboardHookThread
 * Method:    resetHotKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_alfah_popup_jni_KeyboardHookThread_resetHotKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
